openapi: 3.0.0
info:
  title: Listings API
  version: 1.0.0
  description: API for managing property and experience listings

components:
  securitySchemes:
    CognitoAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    Listing:
      type: object
      properties:
        listingId:
          type: string
        listingType:
          type: string
        name:
          type: string
        address:
          type: string
        city:
          type: string
        photoAddressList:
          type: array
          items:
            type: string
        category:
          type: string
        price:
          type: number
          format: float
        calendar:
          type: array
          items:
            $ref: '#/components/schemas/CalendarEntry'
        hostInformation:
          type: string
    CalendarEntry:
      type: object
      properties:
        date:
          type: string
        available:
          type: boolean
        price:
          type: number
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
        details:
          type: string

paths:
  /listings/create:
    post:
      summary: Create a new listing.
      operationId: createListing
      security:
        - CognitoAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
              examples:
                success:
                  summary: A successful response
                  value:
                    listingId: "LISTING#123"
                    listingType: "STAY"
                    name: "Cozy 2 Bedroom in Central Park"
                    address: "123 Park Ave, New York, NY"
                    city: "New York"
                    photoAddressList: ["http://example.com/photo1.jpg", "http://example.com/photo2.jpg"]
                    category: "Luxury"
                    price: 350
                    calendar:
                      - date: "2023-01-01"
                        available: true
                        price: 375
                      - date: "2023-01-02"
                        available: false
                        price: 375
                    hostInformation: "HOST#123"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                badRequest:
                  summary: Bad Request Example
                  value:
                    message: "Invalid listing data"
                    code: 400
                    details: "The provided listing data is invalid."
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                serverError:
                  summary: Internal Server Error Example
                  value:
                    message: "Internal server error"
                    code: 500
                    details: "An unexpected error occurred while processing the request."
