openapi: 3.0.0
info:
  title: Listings API
  version: 1.0.0
  description: API for managing property and experience listings

components:
  securitySchemes:
    CognitoAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    Listing:
      type: object
      properties:
        listingId:
          type: string
        listingType:
          type: string
        name:
          type: string
        address:
          type: string
        city:
          type: string
        photoAddressList:
          type: array
          items:
            type: string
        category:
          type: string
        price:
          type: number
          format: float
        calendar:
          type: array
          items:
            $ref: '#/components/schemas/CalendarEntry'
        hostInformation:
          type: string
    CalendarEntry:
      type: object
      properties:
        date:
          type: string
        available:
          type: boolean
        price:
          type: number
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
        details:
          type: string

paths:
  /listings/create:
    post:
      summary: Create a new listing.
      operationId: createListing
      security:
        - CognitoAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
 /listings/get/{listingId}:
    get:
      summary: Retrieve listing information by listing ID.
      operationId: getListingById
      parameters:
        - name: listingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'